$(window).on('load',function(){$('.csr-img-slider').owlCarousel({items:1,lazyLoad:!0,loop:!0,dots:!0,margin:0,nav:!0,mouseDrag:!0,touchDrag:!0,smartSpeed:600,autoplay:!0,autoplayTimeout:8000,autoplaySpeed:1000})});$(document).ready(function(){$('body').addClass("site-open");$('.main-nav ul li:has(ul)').addClass('submenu');$('.main-nav ul i').click(function(){$(this).parent('li').toggleClass('open');$(this).parent('li').children('ul').slideToggle()})
$('.mob-btn').click(function(){if(!$('body').hasClass('show-menu')){$('body').addClass('show-menu')}else{$('body').removeClass('show-menu')}});$('.overlay,.close-menu-btn,.eligible-menu ').click(function(){if($('body').hasClass('show-menu')){$('body').removeClass('show-menu')}})});$(document).ready(function(){$(".size_chart").hide();$("#option1").show();$("#size_select").change(function(){$('.size_chart').hide();$(".size_chart").removeClass('open');$('#'+$(this).val()).show();$('#'+$(this).val()).addClass("open")});var didScroll;var lastScrollTop=0;var delta=5;var navbarHeight=$('header').outerHeight();$(window).scroll(function(event){didScroll=!0});setInterval(function(){if(didScroll){hasScrolled();didScroll=!1}},250);function hasScrolled(){var st=$(this).scrollTop();if(Math.abs(lastScrollTop-st)<=delta)
return;if(st>lastScrollTop&&st>navbarHeight){$('header').removeClass('nav-down').addClass('nav-up');$("body").trigger("click")}else{if(st+$(window).height()<$(document).height()){$('header').removeClass('nav-up').addClass('nav-down')}}
lastScrollTop=st}
$(window).on('load resize scroll',function(event){var scrollValue=$(window).scrollTop();var offset=$('[data-spy="affix"]').attr('data-offset-top');if(scrollValue>offset){$('[data-spy="affix"]').addClass('affix-top');var width=$('[data-spy="affix"]').parent().width()}else{$('[data-spy="affix"]').removeClass('affix-top')}});$(function(){$(".head-search").on("click",function(e){$(".search-box").addClass("open");$("body").addClass("open");e.stopPropagation()
$(".search-field").click(function(event){event.stopImmediatePropagation()})});$(document).on("click",function(e){if($(e.target).is(".search-box")===!1){$(".search-box").removeClass("open");$("body").removeClass("open")}})});if($(window).width()<992){$(".left-wrapper").on("click",function(e){$(this).toggleClass("show")})}
$(document).on('mouseup tap touchstart click',function(e){var container=$(".left-wrapper");if(!container.is(e.target)&&container.has(e.target).length===0){container.removeClass("show")}});if($(window).width()>1199){$('header .header-right nav > ul>li > a').on('mouseenter',function(){$('body').removeClass('megamenu_open');$('header .header-right nav > ul li.mega_menu._show').removeClass('_show')});$('header').on('mouseleave',function(){$('body').removeClass('megamenu_open');$('header .header-right nav > ul li.mega_menu._show').removeClass('_show')});$('header .header-right nav > ul li.mega_menu>a').on('mouseenter',function(){if($('body').hasClass('megamenu_open')){$('body').removeClass('megamenu_open')}else{$('body').addClass('megamenu_open')}
$('header .header-right nav > ul li.mega_menu._show').removeClass('_show');$(this).closest('li').addClass('_show')});var container=$("header .header-right nav > ul li.mega_menu");$(document).mouseup(function(e){if(!container.is(e.target)&&container.has(e.target).length===0){$('body').removeClass('megamenu_open');$('header .header-right nav > ul li.mega_menu._show').removeClass('_show')}})}
if($(window).width()<1199){$("header .header-right nav > ul li.mega_menu>a").click(function(event){if($(this).is('a')){$(this).next().slideToggle();return!1}})}
if(window.innerWidth<768){$('.home-mobile-slider').owlCarousel({items:1,lazyLoad:!0,loop:!0,dots:!0,margin:10,nav:!1,mouseDrag:!0,touchDrag:!0,smartSpeed:600,autoplay:!0,autoplayTimeout:8000,autoplaySpeed:1000});$(".top-colm h6").click(function(){$(this).toggleClass("collapsed");$(this).next(".mob").slideToggle("intro")})}
$('.client-profile').owlCarousel({items:1,lazyLoad:!0,loop:!0,dots:!0,margin:0,nav:!0,mouseDrag:!1,touchDrag:!1,smartSpeed:600,autoplay:!0,autoplayTimeout:10000,autoplaySpeed:1000,animateOut:'fadeOut',animateIn:'fadeIn'});var a=0;$(window).scroll(function(){var oTop=$('.home-pravasi-chitty').offset().top-window.innerHeight;if(a==0&&$(window).scrollTop()>oTop){$('.counter-value').each(function(){var $this=$(this),countTo=$this.attr('data-count');$({countNum:$this.text()}).animate({countNum:countTo},{duration:1000,easing:'swing',step:function(){$this.text(Math.floor(this.countNum))},complete:function(){$this.text(this.countNum)}})});a=1}});$(function(){var oTop1=$('.chit-status1').offset().top-window.innerHeight;if(a==0&&$(window).scrollTop()>oTop1){$('.counter-value').each(function(){var $this=$(this),countTo=$this.attr('data-count');$({countNum:$this.text()}).animate({countNum:countTo},{duration:1000,easing:'swing',step:function(){$this.text(Math.floor(this.countNum))},complete:function(){$this.text(this.countNum)}})});a=1}})});var images=document.querySelectorAll("[data-src]");var amine_elem=document.querySelectorAll(".synonix-anim,.synonix-anim-text");var config={rootMargin:"0px 0px 50px 0px",threshold:0};var observer=new IntersectionObserver(function(entries,self){for(var i=0;i<entries.length;i++){if(entries[i].isIntersecting){preloadImage(entries[i].target);self.unobserve(entries[i].target)}}},config);for(var i=0;i<images.length;i++){observer.observe(images[i])}
function preloadImage(img){var src=img.getAttribute("data-src");if(!src){return}
if(img.tagName==="IMG")img.src=src;else img.style.backgroundImage="url("+src+")"}
var observer2=new IntersectionObserver(function(entries,self){for(var i=0;i<entries.length;i++){if(entries[i].isIntersecting){addanimations(entries[i].target,i);self.unobserve(entries[i].target)}}},config);for(var i=0;i<amine_elem.length;i++){observer2.observe(amine_elem[i])}
function addanimations(elem,indx){setTimeout(function(){$(elem).addClass('anime')},200*indx)}
var selectricOptions={disableOnMobile:!1,};$(function(){$('.selectric-select').selectric(selectricOptions)});$(".select2").select2({});if($('main').hasClass("home-page")){$("body").addClass("home")}